create table clients (
  id uuid default gen_random_uuid() primary key,
  business_name text not null,
  owner_name text,
  phone text,
  email text,
  city text,
  state text,
  niche text,
  status text default 'Prospect',
  one_time_fee_collected boolean default false,
  one_time_fee_amount numeric(10,2),
  monthly_recurring numeric(10,2),
  demo_site_url text,
  live_site_url text,
  domain text,
  vercel_project_name text,
  google_drive_url text,
  notes text,
  date_added timestamp with time zone default now(),
  date_closed timestamp with time zone,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);
